### ISSUE TITLE
Failing to parse user and password when password contains %

### ISSUE THREAD

**Issue by sliors** [emc-isilon/pike#116]
https://github.com/emc-isilon/pike/blob/2fbf3dc7ff353c675e025892b45eb923d014b752/pike/auth.py#L45

**Comment by kvv81** [comment]
`user, password = creds.split("%", 1) `

**Comment by isi-mfurer** [comment]
Fix delivered in 0.3.14; thanks for reporting this issue and suggesting a solution.

https://pypi.org/project/pike-smb2/0.3.14/
