### ISSUE TITLE
GSSError: (('An unsupported mechanism was requested', 65536), ('Unknown error', 0))

### ISSUE THREAD

**Issue by patnaiksa** [emc-isilon/pike#15]
Downloaded the latest pike on my CentOS client and configured and build pike per guidelines. Executed pike both using NTLM and Kerberos auth, but failing with below error:
**GSSError: (('An unsupported mechanism was requested', 65536), ('Unknown error', 0))**

Here is a snippet of the screen output:

# make test SERVER=x.x.x.x. SHARE=XXXX CREDS=<domain_name>\\administrator%<passwd>
test_change_notify_file_name (changenotify.ChangeNotifyTest) ... ERROR
test_create_close (compound.CompoundTest) ... ERROR
test_copy_big_file (copychunk.TestServerSideCopy) ... ERROR
test_copy_max_chunks (copychunk.TestServerSideCopy) ... ERROR
test_copy_multiple_chunks (copychunk.TestServerSideCopy) ... ERROR
test_copy_small_file (copychunk.TestServerSideCopy) ... ERROR
test_neg_dst_exc_brl (copychunk.TestServerSideCopy) ... ERROR
test_neg_dst_is_a_dir (copychunk.TestServerSideCopy) ... ERROR
test_neg_dst_no_read (copychunk.TestServerSideCopy) ... ERROR
test_neg_dst_no_write (copychunk.TestServerSideCopy) ... ERROR
test_neg_src_exc_brl (copychunk.TestServerSideCopy) ... ERROR
test_neg_src_no_read (copychunk.TestServerSideCopy) ... ERROR
test_offset_copy_big_file (copychunk.TestServerSideCopy) ... ERROR
test_offset_copy_multiple_chunks (copychunk.TestServerSideCopy) ... ERROR
test_offset_copy_small_file (copychunk.TestServerSideCopy) ... ERROR
test_overlap_15_chunks_4096_overlap (copychunk.TestServerSideCopy) ... ERROR
test_overlap_16_chunks_1024_overlap (copychunk.TestServerSideCopy) ... ERROR
test_overlap_multiple_chunks (copychunk.TestServerSideCopy) ... ERROR
test_same_big_file (copychunk.TestServerSideCopy) ... ERROR
test_same_multiple_chunks (copychunk.TestServerSideCopy) ... ERROR
test_same_offset_big_file (copychunk.TestServerSideCopy) ... ERROR
test_same_offset_multiple_chunks (copychunk.TestServerSideCopy) ... ERROR
test_same_offset_small_file (copychunk.TestServerSideCopy) ... ERROR
test_same_small_file (copychunk.TestServerSideCopy) ... ERROR
test_durable (durable.DurableHandleTest) ... ERROR
test_durable_invalidate (durable.DurableHandleTest) ... ERROR
test_durable_reconnect (durable.DurableHandleTest) ... ERROR
test_durable_reconnect_fails_client_guid (durable.DurableHandleTest) ... ERROR
test_durable_reconnect_v2 (durable.DurableHandleTest) ... ERROR
test_durable_reconnect_v2_fails_client_guid (durable.DurableHandleTest) ... ERROR
test_durable_v2 (durable.DurableHandleTest) ... ERROR
test_durable_v2_invalidate (durable.DurableHandleTest) ... ERROR
test_echo (echo.EchoTest) ... ERROR
test_validate_negotiate_smb3 (ioctl.ValidateNegotiateInfo) ... ERROR
test_lease_break_close_ack (lease.LeaseTest) ... ERROR
test_lease_multiple_connections (lease.LeaseTest) ... ERROR
test_lease_upgrade_break (lease.LeaseTest) ... ERROR
test_allow_zero_byte_write (lock.LockTest) ... ERROR
test_cancel (lock.LockTest) ... ERROR
test_deny_write (lock.LockTest) ... ERROR
test_lock (lock.LockTest) ... ERROR
test_open_bind_close (multichannel.MultiChannelTest) ... skipped 'Capabilities missing: SMB2_GLOBAL_CAP_MULTI_CHANNEL '
test_write_fence_reject_stale (multichannel.MultiChannelTest) ... skipped 'Capabilities missing: SMB2_GLOBAL_CAP_MULTI_CHANNEL '
test_downlevel (negotiate.CapMultichannel) ... ERROR
test_downlevel_no_advert (negotiate.CapMultichannel) ... ERROR
test_smb3 (negotiate.CapMultichannel) ... ERROR
test_smb3_many_capabilities (negotiate.CapMultichannel) ... ERROR
test_smb3_no_advert (negotiate.CapMultichannel) ... ERROR
test_downlevel (negotiate.CapMulticredit) ... ERROR
test_smb21 (negotiate.CapMulticredit) ... ERROR
test_smb3 (negotiate.CapMulticredit) ... ERROR
test_smb3_many_capabilities (negotiate.CapMulticredit) ... ERROR
test_downlevel (negotiate.CapPersistent) ... ERROR
test_downlevel_no_advert (negotiate.CapPersistent) ... ERROR
test_smb3 (negotiate.CapPersistent) ... ERROR
test_smb3_many_capabilities (negotiate.CapPersistent) ... ERROR
test_smb3_no_advert (negotiate.CapPersistent) ... ERROR
test_oplock_break (oplock.OplockTest) ... ERROR
test_create (persistent.Persistent) ... skipped 'Capabilities missing: SMB2_GLOBAL_CAP_PERSISTENT_HANDLES '
test_open_while_disconnected (persistent.Persistent) ... skipped 'Capabilities missing: SMB2_GLOBAL_CAP_PERSISTENT_HANDLES '
test_reconnect (persistent.Persistent) ... skipped 'Capabilities missing: SMB2_GLOBAL_CAP_PERSISTENT_HANDLES '
test_mismatch_0_file_alignment_info (query.QueryTest) ... ERROR
test_mismatch_0_file_all_info (query.QueryTest) ... ERROR
test_mismatch_0_file_basic_info (query.QueryTest) ... ERROR
test_mismatch_0_file_ea_info (query.QueryTest) ... ERROR
test_mismatch_0_file_internal_info (query.QueryTest) ... ERROR
test_mismatch_0_file_mode_info (query.QueryTest) ... ERROR
test_mismatch_0_file_position_info (query.QueryTest) ... ERROR
test_mismatch_0_file_standard_info (query.QueryTest) ... ERROR
test_query_file_alignment_info (query.QueryTest) ... ERROR
test_query_file_all_info (query.QueryTest) ... ERROR
test_query_file_basic_info (query.QueryTest) ... ERROR
test_query_file_ea_info (query.QueryTest) ... ERROR
test_query_file_internal_info (query.QueryTest) ... ERROR
test_query_file_mode_info (query.QueryTest) ... ERROR
test_query_file_position_info (query.QueryTest) ... ERROR
test_query_file_standard_info (query.QueryTest) ... ERROR
test_query_sec_desc_0 (query.QueryTest) ... ERROR
test_file_directory_info (querydirectory.QueryDirectoryTest) ... ERROR
test_specific_name (querydirectory.QueryDirectoryTest) ... ERROR
test_qfid_diff_file (queryondiskid.TestQueryOnDiskID) ... ERROR
test_qfid_functional (queryondiskid.TestQueryOnDiskID) ... ERROR
test_qfid_same_file (queryondiskid.TestQueryOnDiskID) ... ERROR
test_qfid_same_file_seq (queryondiskid.TestQueryOnDiskID) ... ERROR
test_qfid_same_file_seq_delete (queryondiskid.TestQueryOnDiskID) ... ERROR
test_write (readwrite.ReadWriteTest) ... ERROR
test_write_none (readwrite.ReadWriteTest) ... ERROR
test_write_none_access (readwrite.ReadWriteTest) ... ERROR
test_write_none_lease (readwrite.ReadWriteTest) ... ERROR
test_write_none_oplock (readwrite.ReadWriteTest) ... ERROR
test_set_get_reparse_point (reparse.TestReparsePoint) ... ERROR
test_symbolic_link_error_response (reparse.TestReparsePoint) ... ERROR
test_session_logoff (session.SessionTest) ... ERROR
test_set_file_basic_info (set.SetTest) ... ERROR
test_set_file_mode_info (set.SetTest) ... ERROR
test_set_file_name (set.SetTest) ... ERROR
test_set_file_position_info (set.SetTest) ... ERROR
test_tree (tree.TreeTest) ... ERROR
test_appinstanceid (appinstanceid.AppInstanceIdTest) ... skipped 'Capabilities missing: SMB2_GLOBAL_CAP_PERSISTENT_HANDLES '
test_appinstanceid_persistent_with_disconnect (appinstanceid.AppInstanceIdTest) ... skipped 'Capabilities missing: SMB2_GLOBAL_CAP_PERSISTENT_HANDLES '
test_appinstanceid_reconnect_same_clientguid (appinstanceid.AppInstanceIdTest) ... skipped 'Capabilities missing: SMB2_GLOBAL_CAP_PERSISTENT_HANDLES '

======================================================================
ERROR: test_change_notify_file_name (changenotify.ChangeNotifyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pike-master/test/changenotify.py", line 44, in test_change_notify_file_name
    chan, tree = self.tree_connect()
  File "/home/output/stage/usr/lib64/python2.7/site-packages/pike/test.py", line 127, in tree_connect
    chan = conn.session_setup(self.creds)
  File "/home/output/stage/usr/lib64/python2.7/site-packages/pike/model.py", line 709, in session_setup
    domain=domain)
GSSError: (('An unsupported mechanism was requested', 65536), ('Unknown error', 0))

Thanks in advance for any help here.

Regards
Santosh

**Comment by isi-mfurer** [comment]
If you are using NTLM credentials, then you must link against a gss library that supports the NTLM mechanism (currently Heimdall and MIT do not support it). The only available open source library that I'm aware of which supports NTLM and kerberos is the PowerBroker Open (formerly Likewise) package: https://www.powerbrokeropen.org/.

We currently do not test with this library so I can make no guarantee as to its functionality.

You may also try my fork of pike which includes a pure python implementation of ntlm: https://github.com/isi-mfurer/pike/tree/pyntlm

I haven't merged this into the mainline because I'm trying to find time to add ntlmv2 support, but the ntlmv1 should be completely functional and enable the tests to run without building the kerberos library.

**Comment by patnaiksa** [comment]
Thanks isi-mufrer. I used your pike version and that did work with NTLM. I will look forward your code merge to mainline. 

Thanks
Santosh
